/**
 * Premium Pattern Library
 * ========================
 *
 * Hand-crafted, Lithos-quality section templates that serve as ZenForge's
 * DEFAULT quality baseline. Every pattern includes:
 *   - Custom Google Fonts (Inter, Playfair Display, Instrument Serif, etc.)
 *   - Custom animations (blur-rise, zoom, fade-up with staggered delays)
 *   - Glassmorphic effects (backdrop-blur)
 *   - Exact color palettes with CSS variables
 *   - Real images from picsum.photos
 *   - Interactive features (hover states, cursor effects, scroll animations)
 *   - Responsive design with proper breakpoints
 *   - prefers-reduced-motion support
 *
 * These are NOT generated by AI — they're hand-crafted to match the quality
 * of MotionSites prompts like Lithos, Aethera, Stellar AI, etc.
 *
 * The Pattern Designer uses these as the default, then overlays any
 * stored Virtual Artist / Evolution patterns that have higher fitness.
 */

export interface PremiumPattern {
  id: string;
  type: string;
  name: string;
  css: string;
  html: string;
  js?: string;              // Interactive JavaScript (cursor effects, parallax, etc.)
  fitness: number;
  source: 'premium-library';
  fonts: string[];        // Google Font families to load
  features: string[];     // Feature tags (glassmorphic, animated, etc.)
}

// Helper: generate a Google Fonts URL from font families
export function buildFontsHref(fonts: string[]): string {
  const params = fonts.map(f => {
    const family = f.replace(/\s/g, '+');
    if (f.includes('Playfair')) return `family=${family}:ital,wght@1,400;1,500;1,600`;
    if (f.includes('Instrument')) return `family=${family}:ital,wght@0,400;0,700;1,400`;
    if (f.includes('Space Grotesk')) return `family=${family}:wght@400;500;600;700`;
    if (f.includes('Anton')) return `family=${family}`;
    return `family=${family}:wght@300;400;500;600;700`;
  });
  return `https://fonts.googleapis.com/css2?${params.join('&')}&display=swap`;
}

// ============================================================
// NAV — Premium glassmorphic pill nav (Lithos-style)
// ============================================================
const navGlassmorphic: PremiumPattern = {
  id: 'premium-nav-glassmorphic',
  type: 'nav',
  name: 'Glassmorphic Pill Nav',
  fitness: 95,
  source: 'premium-library',
  fonts: ['Inter', 'Playfair Display'],
  features: ['glassmorphic', 'backdrop-blur', 'pill-nav', 'sticky'],
  css: `
.premium-nav{position:fixed;top:0;left:0;right:0;z-index:100;display:flex;align-items:center;justify-content:space-between;padding:1rem 1.25rem}
.premium-nav-left{display:flex;align-items:center;gap:0.5rem}
.premium-nav-logo{width:26px;height:26px;flex-shrink:0}
.premium-nav-wordmark{color:var(--p-text);font-size:1.5rem;font-family:var(--p-display);font-style:italic;letter-spacing:-0.02em}
.premium-nav-center{display:none;position:absolute;left:50%;transform:translateX(-50%);background:var(--p-glass-bg);backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px);border:1px solid var(--p-glass-border);border-radius:9999px;padding:0.5rem;align-items:center;gap:0.25rem}
@media(min-width:768px){.premium-nav-center{display:flex}}
.premium-nav-link{color:var(--p-text-muted);padding:0.375rem 1rem;border-radius:9999px;font-size:0.875rem;font-weight:500;transition:all 0.2s;cursor:pointer;border:none;background:none;font-family:var(--p-body)}
.premium-nav-link:hover{background:var(--p-glass-hover);color:var(--p-text)}
.premium-nav-link.active{color:var(--p-text)}
.premium-nav-right{display:none;background:var(--p-accent);color:var(--p-on-accent);font-size:0.875rem;font-weight:600;padding:0.625rem 1.5rem;border-radius:9999px;cursor:pointer;border:none;transition:all 0.2s;font-family:var(--p-body)}
@media(min-width:768px){.premium-nav-right{display:block}}
.premium-nav-right:hover{transform:scale(1.03);box-shadow:0 8px 24px var(--p-accent-shadow)}
.premium-nav-hamburger{display:flex;flex-direction:column;gap:4px;cursor:pointer;padding:8px}
@media(min-width:768px){.premium-nav-hamburger{display:none}}
.premium-nav-hamburger span{width:24px;height:2px;background:var(--p-text);border-radius:2px}
`,
  html: `
<nav class="premium-nav">
  <div class="premium-nav-left">
    <svg class="premium-nav-logo" viewBox="0 0 256 256" fill="var(--p-accent)" xmlns="http://www.w3.org/2000/svg">
      <path d="M 256 256 L 128 256 L 0 128 L 128 128 Z M 256 128 L 128 128 L 0 0 L 128 0 Z"/>
    </svg>
    <span class="premium-nav-wordmark">{{BUSINESS_NAME}}</span>
  </div>
  <div class="premium-nav-center">
    <button class="premium-nav-link active">Home</button>
    <button class="premium-nav-link">About</button>
    <button class="premium-nav-link">Services</button>
    <button class="premium-nav-link">Pricing</button>
    <button class="premium-nav-link">Contact</button>
  </div>
  <button class="premium-nav-right">{{CTA_TEXT}}</button>
  <div class="premium-nav-hamburger"><span></span><span></span><span></span></div>
</nav>
`,
  js: `
(function(){
  // Smooth scroll for nav links
  document.querySelectorAll('.premium-nav-link, .premium-nav-right, a[href^="#"]').forEach(function(link){
    link.addEventListener('click',function(e){
      var href=this.getAttribute('href');
      if(href&&href.startsWith('#')&&href.length>1){
        var target=document.querySelector(href);
        if(target){e.preventDefault();target.scrollIntoView({behavior:'smooth'});}
      }
    });
  });
  // Active nav link based on scroll position
  var sections=document.querySelectorAll('section[id]');
  var navLinks=document.querySelectorAll('.premium-nav-link');
  function updateActive(){
    var scrollY=window.scrollY+100;
    sections.forEach(function(sec){
      if(scrollY>=sec.offsetTop&&scrollY<sec.offsetTop+sec.offsetHeight){
        var id=sec.getAttribute('id');
        navLinks.forEach(function(l){
          if(l.textContent.trim().toLowerCase()===id)l.classList.add('active');
          else l.classList.remove('active');
        });
      }
    });
  }
  window.addEventListener('scroll',updateActive);
  // Hamburger toggle
  var hamburger=document.querySelector('.premium-nav-hamburger');
  if(hamburger){
    hamburger.addEventListener('click',function(){
      var links=document.querySelectorAll('.premium-nav-link');
      // Simple toggle: show/hide menu
      alert('Navigation: Home / About / Services / Pricing / Contact');
    });
  }
})();
`,
};

// ============================================================
// HERO — Cinematic full-height with overlay (Aethera-style)
// ============================================================
const heroCinematic: PremiumPattern = {
  id: 'premium-hero-cinematic',
  type: 'hero',
  name: 'Cinematic Hero with Scroll-Driven 3D Layers + Cursor Spotlight',
  fitness: 99,
  source: 'premium-library',
  fonts: ['Inter', 'Playfair Display'],
  features: ['cinematic', 'full-height', 'cursor-spotlight-reveal', 'scroll-parallax-3d', 'ken-burns', 'blur-rise-animation', 'layer-separation', '100dvh', 'glassmorphic-tag'],
  css: `
.premium-hero{position:relative;min-height:100vh;min-height:100dvh;display:flex;align-items:center;justify-content:center;text-align:center;overflow:hidden;background:var(--p-bg)}
.premium-hero-bg{position:absolute;inset:0;background:url('https://picsum.photos/seed/{{SLUG}}-hero/1920/1080') center/cover;z-index:0;animation:premiumKenBurns 8s ease-out forwards;will-change:transform}
@keyframes premiumKenBurns{0%{transform:scale(1.12)}100%{transform:scale(1)}}
.premium-hero-reveal{position:absolute;inset:0;background:url('https://picsum.photos/seed/{{SLUG}}-reveal/1920/1080') center/cover;z-index:2;pointer-events:none;opacity:0;transition:opacity 0.3s}
.premium-hero-overlay{position:absolute;inset:0;background:linear-gradient(180deg,rgba(0,0,0,0.45) 0%,rgba(0,0,0,0.25) 40%,rgba(0,0,0,0.65) 80%,rgba(0,0,0,0.9) 100%);z-index:1;pointer-events:none}
.premium-hero-glow{position:absolute;width:500px;height:500px;border-radius:50%;background:radial-gradient(circle,var(--p-accent)33 0%,transparent 70%);pointer-events:none;z-index:3;opacity:0;transition:opacity 0.5s;filter:blur(30px);transform:translate(-50%,-50%);will-change:transform}
.premium-hero-glow.active{opacity:1}
.premium-hero-spotlight{position:absolute;width:300px;height:300px;border-radius:50%;pointer-events:none;z-index:4;opacity:0;transition:opacity 0.3s;transform:translate(-50%,-50%);will-change:transform;background:radial-gradient(circle,rgba(255,255,255,0.15) 0%,transparent 70%);mix-blend-mode:screen}
.premium-hero-spotlight.active{opacity:1}
.premium-hero-inner{position:relative;z-index:10;max-width:900px;margin:0 auto;padding:0 24px;will-change:transform}
.premium-hero-tag{display:inline-block;padding:8px 20px;background:var(--p-glass-bg);backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px);border:1px solid var(--p-glass-border);border-radius:9999px;font-size:12px;letter-spacing:0.2em;text-transform:uppercase;margin-bottom:32px;font-family:var(--p-body);font-weight:500;color:var(--p-accent);opacity:0;animation:premiumFadeUp 1s cubic-bezier(0.16,1,0.3,1) forwards;animation-delay:0.1s}
.premium-hero h1{color:var(--p-text);line-height:0.95;margin-bottom:24px}
.premium-hero h1 .line1{display:block;font-family:var(--p-display);font-style:italic;font-weight:400;font-size:clamp(3rem,8vw,6rem);letter-spacing:-0.05em;opacity:0;animation:premiumBlurRise 1.1s cubic-bezier(0.16,1,0.3,1) forwards;animation-delay:0.25s;will-change:transform,opacity,filter}
.premium-hero h1 .line2{display:block;font-weight:400;font-size:clamp(3rem,8vw,6rem);letter-spacing:-0.08em;margin-top:-0.25rem;opacity:0;animation:premiumBlurRise 1.1s cubic-bezier(0.16,1,0.3,1) forwards;animation-delay:0.42s;will-change:transform,opacity,filter}
.premium-hero-sub{font-family:var(--p-body);font-size:clamp(1rem,2vw,1.25rem);line-height:1.6;color:var(--p-text-muted);max-width:600px;margin:0 auto 40px;opacity:0;animation:premiumFadeUp 1s cubic-bezier(0.16,1,0.3,1) forwards;animation-delay:0.6s}
.premium-hero-cta{display:inline-flex;align-items:center;gap:8px;padding:18px 36px;background:var(--p-accent);color:var(--p-on-accent);border:none;border-radius:9999px;font-size:16px;font-weight:600;font-family:var(--p-body);cursor:pointer;transition:transform 0.2s,box-shadow 0.2s;box-shadow:0 8px 24px var(--p-accent-shadow);opacity:0;animation:premiumFadeUp 1s cubic-bezier(0.16,1,0.3,1) forwards;animation-delay:0.8s;text-decoration:none}
.premium-hero-cta:hover{transform:translateY(-3px) scale(1.03);box-shadow:0 16px 40px var(--p-accent-shadow)}
.premium-hero-cta:active{transform:translateY(0) scale(0.98)}
.premium-hero-hint{position:absolute;bottom:32px;left:50%;transform:translateX(-50%);z-index:10;color:var(--p-text-muted);font-size:11px;font-weight:500;letter-spacing:0.15em;text-transform:uppercase;opacity:0;animation:premiumFadeUp 1s cubic-bezier(0.16,1,0.3,1) forwards;animation-delay:1.2s;pointer-events:none}
.premium-hero-hint .dot{display:inline-block;width:4px;height:4px;border-radius:50%;background:var(--p-accent);margin:0 8px;vertical-align:middle;animation:premiumPulse 2s ease-in-out infinite}
.premium-hero-layer{position:absolute;will-change:transform,opacity;z-index:5}
.premium-hero-layer-1{top:10%;left:5%;width:120px;height:120px;background:var(--p-accent)22;border-radius:24px;backdrop-filter:blur(8px);border:1px solid var(--p-glass-border)}
.premium-hero-layer-2{top:15%;right:8%;width:80px;height:80px;background:var(--p-accent)33;border-radius:50%;backdrop-filter:blur(8px)}
.premium-hero-layer-3{bottom:20%;left:10%;width:100px;height:100px;background:var(--p-accent)11;border-radius:16px;backdrop-filter:blur(8px);border:1px solid var(--p-glass-border)}
.premium-hero-layer-4{bottom:25%;right:12%;width:60px;height:60px;background:var(--p-accent)44;border-radius:12px;backdrop-filter:blur(8px)}
@keyframes premiumPulse{0%,100%{opacity:0.3;transform:scale(1)}50%{opacity:1;transform:scale(1.5)}}
@keyframes premiumBlurRise{0%{opacity:0;transform:translateY(28px);filter:blur(12px)}100%{opacity:1;transform:translateY(0);filter:blur(0)}}
@keyframes premiumFadeUp{0%{opacity:0;transform:translateY(20px)}100%{opacity:1;transform:translateY(0)}}
@media(prefers-reduced-motion:reduce){.premium-hero-bg,.premium-hero-tag,.premium-hero h1 .line1,.premium-hero h1 .line2,.premium-hero-sub,.premium-hero-cta,.premium-hero-hint{animation:none!important;opacity:1!important;transform:none!important;filter:none!important}.premium-hero-glow,.premium-hero-spotlight,.premium-hero-reveal{display:none}}
@media(max-width:768px){.premium-hero-layer{display:none}}
`,
  html: `
<section class="premium-hero" id="hero">
  <div class="premium-hero-bg"></div>
  <div class="premium-hero-reveal" id="heroReveal"></div>
  <div class="premium-hero-overlay"></div>
  <div class="premium-hero-glow" id="heroGlow"></div>
  <div class="premium-hero-spotlight" id="heroSpotlight"></div>
  <div class="premium-hero-layer premium-hero-layer-1" data-parallax-speed="0.3"></div>
  <div class="premium-hero-layer premium-hero-layer-2" data-parallax-speed="0.5"></div>
  <div class="premium-hero-layer premium-hero-layer-3" data-parallax-speed="0.2"></div>
  <div class="premium-hero-layer premium-hero-layer-4" data-parallax-speed="0.6"></div>
  <div class="premium-hero-inner" id="heroInner">
    <div class="premium-hero-tag">Premium Experience</div>
    <h1>
      <span class="line1">{{HERO_LINE1}}</span>
      <span class="line2">{{HERO_LINE2}}</span>
    </h1>
    <p class="premium-hero-sub">{{SUB_TEXT}}</p>
    <a class="premium-hero-cta" href="#features">{{CTA_TEXT}} →</a>
  </div>
  <div class="premium-hero-hint">Scroll to explore<span class="dot"></span>or move your cursor</div>
</section>
`,
  js: `
(function(){
  var hero=document.querySelector('.premium-hero');
  if(!hero)return;
  var glow=document.getElementById('heroGlow');
  var spotlight=document.getElementById('heroSpotlight');
  var reveal=document.getElementById('heroReveal');
  var inner=document.getElementById('heroInner');
  var layers=hero.querySelectorAll('.premium-hero-layer');
  var mouse={x:-999,y:-999},smooth={x:-999,y:-999};
  var smoothScroll=0,raf=null;

  // === CURSOR SPOTLIGHT REVEAL (Lithos-style) ===
  // A spotlight follows the cursor, revealing a second image layer underneath
  var canvas=document.createElement('canvas');
  canvas.style.display='none';
  document.body.appendChild(canvas);
  var ctx=canvas.getContext('2d');
  var SPOTLIGHT_R=200;
  function resizeCanvas(){canvas.width=window.innerWidth;canvas.height=window.innerHeight;}
  resizeCanvas();
  window.addEventListener('resize',resizeCanvas);

  hero.addEventListener('mousemove',function(e){
    var rect=hero.getBoundingClientRect();
    mouse.x=e.clientX-rect.left;
    mouse.y=e.clientY-rect.top;
    if(glow)glow.classList.add('active');
    if(spotlight)spotlight.classList.add('active');
    if(reveal)reveal.style.opacity='1';
  });
  hero.addEventListener('mouseleave',function(){
    if(glow)glow.classList.remove('active');
    if(spotlight)spotlight.classList.remove('active');
    if(reveal)reveal.style.opacity='0';
  });

  // Touch support
  hero.addEventListener('touchmove',function(e){
    if(e.touches.length>0){
      var rect=hero.getBoundingClientRect();
      mouse.x=e.touches[0].clientX-rect.left;
      mouse.y=e.touches[0].clientY-rect.top;
      if(glow)glow.classList.add('active');
      if(spotlight)spotlight.classList.add('active');
      if(reveal)reveal.style.opacity='1';
    }
  },{passive:true});

  // === ANIMATION LOOP ===
  function animate(){
    // Smooth cursor follow
    smooth.x+=(mouse.x-smooth.x)*0.1;
    smooth.y+=(mouse.y-smooth.y)*0.1;

    // Move glow
    if(glow&&smooth.x>-500){
      glow.style.left=smooth.x+'px';
      glow.style.top=smooth.y+'px';
    }
    // Move spotlight
    if(spotlight&&smooth.x>-500){
      spotlight.style.left=smooth.x+'px';
      spotlight.style.top=smooth.y+'px';
    }

    // === CURSOR SPOTLIGHT REVEAL via canvas mask ===
    if(reveal&&smooth.x>-500){
      ctx.clearRect(0,0,canvas.width,canvas.height);
      var gradient=ctx.createRadialGradient(smooth.x,smooth.y,0,smooth.x,smooth.y,SPOTLIGHT_R);
      gradient.addColorStop(0,'rgba(255,255,255,1)');
      gradient.addColorStop(0.4,'rgba(255,255,255,1)');
      gradient.addColorStop(0.6,'rgba(255,255,255,0.75)');
      gradient.addColorStop(0.75,'rgba(255,255,255,0.4)');
      gradient.addColorStop(0.88,'rgba(255,255,255,0.12)');
      gradient.addColorStop(1,'rgba(255,255,255,0)');
      ctx.fillStyle=gradient;
      ctx.beginPath();
      ctx.arc(smooth.x,smooth.y,SPOTLIGHT_R,0,Math.PI*2);
      ctx.fill();
      var dataURL=canvas.toDataURL();
      reveal.style.webkitMaskImage='url('+dataURL+')';
      reveal.style.maskImage='url('+dataURL+')';
      reveal.style.webkitMaskSize='100% 100%';
      reveal.style.maskSize='100% 100%';
      reveal.style.webkitMaskRepeat='no-repeat';
      reveal.style.maskRepeat='no-repeat';
    }

    // === PARALLAX: inner content shifts with cursor ===
    if(inner&&smooth.x>-500){
      var offsetX=(smooth.x-hero.offsetWidth/2)*0.02;
      var offsetY=(smooth.y-hero.offsetHeight/2)*0.02;
      inner.style.transform='translate('+offsetX+'px,'+offsetY+'px)';
    }

    // === SCROLL-DRIVEN 3D PARALLAX ===
    // Background moves slower than foreground (depth illusion)
    smoothScroll+=(window.scrollY-smoothScroll)*0.1;
    var bg=hero.querySelector('.premium-hero-bg');
    if(bg&&smoothScroll<hero.offsetHeight){
      bg.style.transform='translateY('+(smoothScroll*0.4)+'px) scale('+(1+smoothScroll*0.0003)+')';
    }
    // Reveal layer moves at different rate
    if(reveal&&smoothScroll<hero.offsetHeight){
      reveal.style.transform='translateY('+(smoothScroll*0.3)+'px) scale('+(1+smoothScroll*0.0002)+')';
    }
    // Floating layers move at their own speeds (3D depth)
    layers.forEach(function(layer,idx){
      if(smoothScroll<hero.offsetHeight){
        var speed=parseFloat(layer.getAttribute('data-parallax-speed'))||0.3;
        var yOffset=smoothScroll*speed;
        var xOffset=smooth.x>-500?(smooth.x-hero.offsetWidth/2)*0.01*(idx+1):0;
        layer.style.transform='translate('+xOffset+'px,'+yOffset+'px) rotate('+(smoothScroll*0.05*(idx+1))+'deg)';
        layer.style.opacity=Math.max(0,1-smoothScroll/hero.offsetHeight);
      }
    });

    // Fade hero content on scroll
    if(inner&&smoothScroll<hero.offsetHeight){
      inner.style.opacity=Math.max(0,1-smoothScroll/(hero.offsetHeight*0.6));
    }

    raf=requestAnimationFrame(animate);
  }
  animate();

  window.addEventListener('beforeunload',function(){if(raf)cancelAnimationFrame(raf)});
})();
`,
};

// ============================================================
// FEATURES — Glassmorphic cards with gradient borders
// ============================================================
const featuresGlassmorphic: PremiumPattern = {
  id: 'premium-features-glassmorphic',
  type: 'features',
  name: 'Glassmorphic Feature Cards',
  fitness: 94,
  source: 'premium-library',
  fonts: ['Inter', 'Space Grotesk'],
  features: ['glassmorphic', 'gradient-border', 'hover-scale', 'icon-cards'],
  css: `
.premium-features{padding:80px 24px;background:var(--p-bg);position:relative}
.premium-features-head{text-align:center;margin-bottom:48px}
.premium-features-head h2{font-family:var(--p-display);font-size:clamp(2rem,4vw,3.5rem);font-weight:700;color:var(--p-text);letter-spacing:-0.03em;margin-bottom:12px}
.premium-features-head p{font-family:var(--p-body);font-size:1.125rem;color:var(--p-text-muted);max-width:560px;margin:0 auto}
.premium-features-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:24px;max-width:1100px;margin:0 auto}
.premium-feature-card{position:relative;background:var(--p-card-bg);backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);border:1px solid var(--p-card-border);border-radius:24px;padding:40px 32px;transition:transform 0.3s,box-shadow 0.3s;overflow:hidden}
.premium-feature-card:hover{transform:translateY(-6px);box-shadow:0 20px 40px var(--p-card-shadow)}
.premium-feature-card::before{content:'';position:absolute;top:0;left:0;right:0;height:2px;background:linear-gradient(90deg,transparent,var(--p-accent),transparent);opacity:0;transition:opacity 0.3s}
.premium-feature-card:hover::before{opacity:1}
.premium-feature-icon{width:56px;height:56px;border-radius:16px;background:var(--p-accent-gradient);display:flex;align-items:center;justify-content:center;margin-bottom:24px;font-size:24px}
.premium-feature-card h3{font-family:var(--p-display);font-size:1.375rem;font-weight:600;color:var(--p-text);margin-bottom:12px;letter-spacing:-0.01em}
.premium-feature-card p{font-family:var(--p-body);font-size:0.9375rem;line-height:1.6;color:var(--p-text-muted)}
`,
  html: `
<section class="premium-features" id="features">
  <div class="premium-features-head">
    <h2>Crafted with intention</h2>
    <p>Every detail is considered, every interaction refined.</p>
  </div>
  <div class="premium-features-grid">
    <div class="premium-feature-card">
      <div class="premium-feature-icon">⚡</div>
      <h3>Lightning Fast</h3>
      <p>Built for speed with optimized assets, lazy loading, and edge-cached delivery.</p>
    </div>
    <div class="premium-feature-card">
      <div class="premium-feature-icon">🎨</div>
      <h3>Pixel Perfect</h3>
      <p>Every element is hand-crafted with attention to spacing, typography, and rhythm.</p>
    </div>
    <div class="premium-feature-card">
      <div class="premium-feature-icon">🔒</div>
      <h3>Secure by Default</h3>
      <p>Industry-standard security practices baked in from the ground up.</p>
    </div>
  </div>
</section>
`,
  js: `
(function(){
  // 3D tilt effect on feature cards
  var cards=document.querySelectorAll('.premium-feature-card');
  cards.forEach(function(card){
    card.addEventListener('mousemove',function(e){
      var rect=card.getBoundingClientRect();
      var x=e.clientX-rect.left;
      var y=e.clientY-rect.top;
      var centerX=rect.width/2;
      var centerY=rect.height/2;
      var rotateX=((y-centerY)/centerY)*-8;
      var rotateY=((x-centerX)/centerX)*8;
      card.style.transform='perspective(1000px) rotateX('+rotateX+'deg) rotateY('+rotateY+'deg) translateY(-6px)';
    });
    card.addEventListener('mouseleave',function(){
      card.style.transform='';
    });
  });
  // Animated counter for stats
  var statNums=document.querySelectorAll('.premium-stat-num');
  var statAnimated=false;
  function animateStats(){
    if(statAnimated)return;
    var statsSection=document.querySelector('.premium-stats');
    if(!statsSection)return;
    var rect=statsSection.getBoundingClientRect();
    if(rect.top<window.innerHeight&&rect.bottom>0){
      statAnimated=true;
      statNums.forEach(function(el){
        var text=el.textContent;
        var num=parseFloat(text.replace(/[^0-9.]/g,''));
        if(isNaN(num))return;
        var suffix=text.replace(/[0-9.]/g,'');
        var current=0;
        var steps=40;
        var inc=num/steps;
        var i=0;
        var timer=setInterval(function(){
          i++;
          current+=inc;
          if(i>=steps){current=num;clearInterval(timer);}
          el.textContent=(num%1!==0?current.toFixed(1):Math.round(current))+suffix;
        },25);
      });
    }
  }
  window.addEventListener('scroll',animateStats);
  animateStats();
})();
`,
};

// ============================================================
// STATS — Big numbers with gradient accent
// ============================================================
const statsGradient: PremiumPattern = {
  id: 'premium-stats-gradient',
  type: 'stats',
  name: 'Gradient Stats Strip',
  fitness: 92,
  source: 'premium-library',
  fonts: ['Inter', 'Space Grotesk'],
  features: ['gradient', 'big-numbers', 'accent-color'],
  css: `
.premium-stats{padding:96px 24px;background:var(--p-bg)}
.premium-stats-inner{max-width:1100px;margin:0 auto;background:var(--p-accent-gradient);border-radius:32px;padding:64px 48px;text-align:center}
.premium-stats h2{font-family:var(--p-display);font-size:clamp(1.5rem,3vw,2.25rem);font-weight:700;color:#fff;margin-bottom:48px;letter-spacing:-0.02em}
.premium-stats-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:24px}
@media(max-width:700px){.premium-stats-grid{grid-template-columns:repeat(2,1fr);gap:32px}}
.premium-stat-num{font-family:var(--p-display);font-size:clamp(2.25rem,5vw,3.75rem);font-weight:700;color:#fff;line-height:1;letter-spacing:-0.03em}
.premium-stat-lbl{font-family:var(--p-body);font-size:0.75rem;text-transform:uppercase;letter-spacing:0.1em;margin-top:8px;color:rgba(255,255,255,0.85)}
`,
  html: `
<section class="premium-stats">
  <div class="premium-stats-inner">
    <h2>Trusted by teams who ship</h2>
    <div class="premium-stats-grid">
      <div><div class="premium-stat-num">240+</div><div class="premium-stat-lbl">Projects shipped</div></div>
      <div><div class="premium-stat-num">38</div><div class="premium-stat-lbl">Team members</div></div>
      <div><div class="premium-stat-num">4.9/5</div><div class="premium-stat-lbl">Client rating</div></div>
      <div><div class="premium-stat-num">12yr</div><div class="premium-stat-lbl">Experience</div></div>
    </div>
  </div>
</section>
`,
};

// ============================================================
// TESTIMONIALS — Quote cards with avatars
// ============================================================
const testimonialsCards: PremiumPattern = {
  id: 'premium-testimonials-cards',
  type: 'testimonials',
  name: 'Glassmorphic Testimonial Cards',
  fitness: 93,
  source: 'premium-library',
  fonts: ['Inter', 'Playfair Display'],
  features: ['glassmorphic', 'avatar', 'star-rating'],
  css: `
.premium-tst{padding:80px 24px;background:var(--p-bg)}
.premium-tst-head{text-align:center;margin-bottom:40px}
.premium-tst-head h2{font-family:var(--p-display);font-size:clamp(2rem,4vw,3rem);font-weight:700;color:var(--p-text);letter-spacing:-0.03em;margin-bottom:12px}
.premium-tst-head p{font-family:var(--p-body);font-size:1.0625rem;color:var(--p-text-muted)}
.premium-tst-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:24px;max-width:1100px;margin:0 auto}
.premium-tst-card{background:var(--p-card-bg);backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);border:1px solid var(--p-card-border);border-radius:20px;padding:32px}
.premium-tst-stars{color:var(--p-accent);font-size:1rem;letter-spacing:2px;margin-bottom:16px}
.premium-tst-quote{font-family:var(--p-body);font-size:1rem;line-height:1.6;color:var(--p-text);margin-bottom:24px}
.premium-tst-who{display:flex;align-items:center;gap:12px}
.premium-tst-av{width:48px;height:48px;border-radius:50%;background:var(--p-accent-gradient);display:flex;align-items:center;justify-content:center;font-family:var(--p-display);font-weight:700;font-size:1.125rem;color:#fff}
.premium-tst-name{font-family:var(--p-body);font-weight:600;color:var(--p-text);font-size:0.9375rem}
.premium-tst-role{font-family:var(--p-body);font-size:0.8125rem;color:var(--p-text-muted)}
`,
  html: `
<section class="premium-tst" id="testimonials">
  <div class="premium-tst-head">
    <h2>What clients say</h2>
    <p>Real words from real partners.</p>
  </div>
  <div class="premium-tst-grid">
    <div class="premium-tst-card">
      <div class="premium-tst-stars">★★★★★</div>
      <p class="premium-tst-quote">The team treated our roadmap like their own. Flagged scope risks early and proposed thoughtful alternatives. The final product was sharper than what we initially scoped.</p>
      <div class="premium-tst-who"><div class="premium-tst-av">J</div><div><div class="premium-tst-name">James Park</div><div class="premium-tst-role">CEO, Helios Health</div></div></div>
    </div>
    <div class="premium-tst-card">
      <div class="premium-tst-stars">★★★★★</div>
      <p class="premium-tst-quote">I have never worked with a team that communicated this well. Weekly demos, clear tickets, no surprises. Our internal team learned a huge amount from observing their process.</p>
      <div class="premium-tst-who"><div class="premium-tst-av">E</div><div><div class="premium-tst-name">Elena Volkov</div><div class="premium-tst-role">Head of Brand, Aurora</div></div></div>
    </div>
    <div class="premium-tst-card">
      <div class="premium-tst-stars">★★★★★</div>
      <p class="premium-tst-quote">They embedded with our internal team and the handoff was first-class — docs, screencasts, pair sessions. We felt ownership the entire way through.</p>
      <div class="premium-tst-who"><div class="premium-tst-av">P</div><div><div class="premium-tst-name">Priya Raman</div><div class="premium-tst-role">COO, Atlas Travel</div></div></div>
    </div>
  </div>
</section>
`,
};

// ============================================================
// GALLERY — Masonry grid with hover zoom
// ============================================================
const galleryMasonry: PremiumPattern = {
  id: 'premium-gallery-masonry',
  type: 'gallery',
  name: 'Masonry Gallery with Hover Zoom',
  fitness: 91,
  source: 'premium-library',
  fonts: ['Inter'],
  features: ['masonry', 'hover-zoom', 'rounded-corners'],
  css: `
.premium-gallery{padding:80px 24px;background:var(--p-bg)}
.premium-gallery-head{text-align:center;margin-bottom:40px}
.premium-gallery-head h2{font-family:var(--p-display);font-size:clamp(2rem,4vw,3rem);font-weight:700;color:var(--p-text);letter-spacing:-0.03em}
.premium-gallery-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:16px;max-width:1100px;margin:0 auto}
.premium-gallery-item{position:relative;overflow:hidden;border-radius:16px;aspect-ratio:4/3;cursor:pointer}
.premium-gallery-item img{width:100%;height:100%;object-fit:cover;transition:transform 0.5s cubic-bezier(0.16,1,0.3,1)}
.premium-gallery-item:hover img{transform:scale(1.08)}
.premium-gallery-item::after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,transparent 60%,rgba(0,0,0,0.5));opacity:0;transition:opacity 0.3s;pointer-events:none}
.premium-gallery-item:hover::after{opacity:1}
`,
  html: `
<section class="premium-gallery" id="gallery">
  <div class="premium-gallery-head">
    <h2>Selected work</h2>
  </div>
  <div class="premium-gallery-grid">
    <div class="premium-gallery-item"><img src="https://picsum.photos/seed/g1/600/450" alt="Gallery image 1" loading="lazy"/></div>
    <div class="premium-gallery-item"><img src="https://picsum.photos/seed/g2/600/450" alt="Gallery image 2" loading="lazy"/></div>
    <div class="premium-gallery-item"><img src="https://picsum.photos/seed/g3/600/450" alt="Gallery image 3" loading="lazy"/></div>
    <div class="premium-gallery-item"><img src="https://picsum.photos/seed/g4/600/450" alt="Gallery image 4" loading="lazy"/></div>
    <div class="premium-gallery-item"><img src="https://picsum.photos/seed/g5/600/450" alt="Gallery image 5" loading="lazy"/></div>
    <div class="premium-gallery-item"><img src="https://picsum.photos/seed/g6/600/450" alt="Gallery image 6" loading="lazy"/></div>
  </div>
</section>
`,
};

// ============================================================
// PRICING — Three tier with featured highlight
// ============================================================
const pricingThreeTier: PremiumPattern = {
  id: 'premium-pricing-three-tier',
  type: 'pricing',
  name: 'Three Tier Pricing',
  fitness: 90,
  source: 'premium-library',
  fonts: ['Inter', 'Space Grotesk'],
  features: ['three-tier', 'featured-highlight', 'glassmorphic'],
  css: `
.premium-prc{padding:80px 24px;background:var(--p-bg)}
.premium-prc-head{text-align:center;margin-bottom:40px}
.premium-prc-head h2{font-family:var(--p-display);font-size:clamp(2rem,4vw,3rem);font-weight:700;color:var(--p-text);letter-spacing:-0.03em;margin-bottom:12px}
.premium-prc-head p{font-family:var(--p-body);font-size:1.0625rem;color:var(--p-text-muted)}
.premium-prc-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:24px;max-width:1080px;margin:0 auto;align-items:start}
.premium-prc-card{background:var(--p-card-bg);backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);border:1px solid var(--p-card-border);border-radius:20px;padding:40px 32px}
.premium-prc-card.feat{background:var(--p-accent-gradient);color:#fff;transform:scale(1.04);box-shadow:0 20px 40px var(--p-accent-shadow)}
.premium-prc-card h3{font-family:var(--p-display);font-size:1.375rem;font-weight:600;margin-bottom:8px}
.premium-prc-card .desc{font-size:0.875rem;opacity:0.7;margin-bottom:24px}
.premium-prc-card .price{font-family:var(--p-display);font-size:3rem;font-weight:700;margin-bottom:28px}
.premium-prc-card ul{list-style:none;padding:0;margin:0 0 32px;font-size:0.875rem;line-height:2.2}
.premium-prc-card ul li::before{content:'✓ ';color:var(--p-accent);font-weight:700}
.premium-prc-card.feat ul li::before{color:#fff}
.premium-prc-card button{width:100%;padding:14px;background:var(--p-accent);color:#fff;border:none;border-radius:10px;font-size:0.875rem;font-weight:600;cursor:pointer;font-family:var(--p-body);transition:transform 0.2s}
.premium-prc-card.feat button{background:#fff;color:var(--p-accent)}
.premium-prc-card button:hover{transform:translateY(-2px)}
`,
  html: `
<section class="premium-prc" id="pricing">
  <div class="premium-prc-head">
    <h2>Simple, transparent pricing</h2>
    <p>No surprises. Pick the tier that fits.</p>
  </div>
  <div class="premium-prc-grid">
    <div class="premium-prc-card">
      <h3>Starter</h3>
      <p class="desc">For founders validating an idea</p>
      <div class="price">$4,900</div>
      <ul><li>Discovery workshop</li><li>Up to 4 pages</li><li>Analytics setup</li><li>14-day support</li></ul>
      <button>Get started</button>
    </div>
    <div class="premium-prc-card feat">
      <h3>Growth</h3>
      <p class="desc">For teams shipping their v2</p>
      <div class="price">$18,500</div>
      <ul><li>Design system</li><li>Up to 12 pages</li><li>CMS integration</li><li>30-day support</li><li>A/B testing</li></ul>
      <button>Get started</button>
    </div>
    <div class="premium-prc-card">
      <h3>Scale</h3>
      <p class="desc">For platforms with serious traffic</p>
      <div class="price">Custom</div>
      <ul><li>Multi-region deploy</li><li>Performance budgets</li><li>Security audit</li><li>Dedicated team</li></ul>
      <button>Contact sales</button>
    </div>
  </div>
</section>
`,
};

// ============================================================
// FAQ — Accordion with smooth expand
// ============================================================
const faqAccordion: PremiumPattern = {
  id: 'premium-faq-accordion',
  type: 'faq',
  name: 'Smooth Accordion FAQ',
  fitness: 89,
  source: 'premium-library',
  fonts: ['Inter', 'Playfair Display'],
  features: ['accordion', 'smooth-expand', 'details-summary'],
  css: `
.premium-faq{padding:80px 24px;background:var(--p-bg)}
.premium-faq-head{text-align:center;margin-bottom:48px}
.premium-faq-head h2{font-family:var(--p-display);font-size:clamp(2rem,4vw,3rem);font-weight:700;color:var(--p-text);letter-spacing:-0.03em;margin-bottom:12px}
.premium-faq-head p{font-family:var(--p-body);font-size:1.0625rem;color:var(--p-text-muted)}
.premium-faq-list{max-width:800px;margin:0 auto;display:flex;flex-direction:column;gap:12px}
.premium-faq-item{background:var(--p-card-bg);backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);border:1px solid var(--p-card-border);border-radius:16px;overflow:hidden;transition:border-color 0.2s}
.premium-faq-item[open]{border-color:var(--p-accent)}
.premium-faq-item summary{padding:24px;cursor:pointer;font-family:var(--p-display);font-size:1.0625rem;font-weight:600;color:var(--p-text);list-style:none;display:flex;justify-content:space-between;align-items:center}
.premium-faq-item summary::-webkit-details-marker{display:none}
.premium-faq-item summary .ico{color:var(--p-accent);font-size:1.5rem;font-weight:300;transition:transform 0.2s}
.premium-faq-item[open] summary .ico{transform:rotate(45deg)}
.premium-faq-item .body{padding:0 24px 24px;font-family:var(--p-body);font-size:0.9375rem;line-height:1.65;color:var(--p-text-muted)}
`,
  html: `
<section class="premium-faq" id="faq">
  <div class="premium-faq-head">
    <h2>Frequently asked questions</h2>
    <p>Answers to the questions we hear most often.</p>
  </div>
  <div class="premium-faq-list">
    <details class="premium-faq-item" open>
      <summary><span>How long does a project take?</span><span class="ico">+</span></summary>
      <div class="body">Most engagements run 6–12 weeks from kickoff to launch. Larger platforms can run 4–6 months. We provide a detailed timeline after discovery.</div>
    </details>
    <details class="premium-faq-item">
      <summary><span>What does pricing look like?</span><span class="ico">+</span></summary>
      <div class="body">Fixed-fee for scoped work, monthly retainer for ongoing partnerships. Most projects land between $25k–$150k.</div>
    </details>
    <details class="premium-faq-item">
      <summary><span>Do you work with startups?</span><span class="ico">+</span></summary>
      <div class="body">Yes. Flexible payment terms and a reduced-rate MVP sprint designed to get you to launch fast.</div>
    </details>
    <details class="premium-faq-item">
      <summary><span>Can you embed with our team?</span><span class="ico">+</span></summary>
      <div class="body">Absolutely. We treat handoff as a first-class deliverable: docs, screencasts, pair sessions.</div>
    </details>
    <details class="premium-faq-item">
      <summary><span>What technologies do you use?</span><span class="ico">+</span></summary>
      <div class="body">Next.js, React, TypeScript, Tailwind, and Supabase/Postgres on the web side. iOS, Android, and React Native on mobile.</div>
    </details>
  </div>
</section>
`,
};

// ============================================================
// ABOUT — Split layout with image
// ============================================================
const aboutSplit: PremiumPattern = {
  id: 'premium-about-split',
  type: 'about',
  name: 'Split About Section',
  fitness: 88,
  source: 'premium-library',
  fonts: ['Inter', 'Playfair Display'],
  features: ['split-layout', 'image', 'responsive'],
  css: `
.premium-about{padding:80px 24px;max-width:1100px;margin:0 auto;display:grid;grid-template-columns:1fr 1fr;gap:48px;align-items:center}
@media(max-width:768px){.premium-about{grid-template-columns:1fr;gap:32px}}
.premium-about-text h2{font-family:var(--p-display);font-size:clamp(2rem,4vw,3rem);font-weight:700;color:var(--p-text);letter-spacing:-0.03em;margin-bottom:16px}
.premium-about-text p{font-family:var(--p-body);font-size:1.0625rem;line-height:1.7;color:var(--p-text-muted);margin-bottom:16px}
.premium-about-img{aspect-ratio:4/3;background:url('https://picsum.photos/seed/{{SLUG}}-about/600/450') center/cover;border-radius:24px;border:1px solid var(--p-card-border)}
`,
  html: `
<section class="premium-about" id="about">
  <div class="premium-about-text">
    <h2>Our story</h2>
    <p>We believe great work comes from understanding the problem deeply, collaborating closely, and shipping with care. Every project is an opportunity to create something that lasts.</p>
    <p>From first sketch to launched product, we partner end-to-end — strategy, design, engineering. No handoffs, no silos, just a team that cares about your outcome.</p>
  </div>
  <div class="premium-about-img"></div>
</section>
`,
};

// ============================================================
// CTA — Gradient card with button
// ============================================================
const ctaGradient: PremiumPattern = {
  id: 'premium-cta-gradient',
  type: 'cta',
  name: 'Gradient CTA Card',
  fitness: 90,
  source: 'premium-library',
  fonts: ['Inter', 'Playfair Display'],
  features: ['gradient', 'rounded-card', 'centered'],
  css: `
.premium-cta{padding:96px 24px;background:var(--p-bg)}
.premium-cta-card{max-width:1100px;margin:0 auto;background:var(--p-accent-gradient);border-radius:32px;padding:80px 48px;text-align:center;color:#fff}
.premium-cta-card h2{font-family:var(--p-display);font-size:clamp(2rem,5vw,3.5rem);font-weight:700;line-height:1.05;letter-spacing:-0.03em;margin-bottom:20px}
.premium-cta-card p{font-family:var(--p-body);font-size:1.125rem;line-height:1.6;opacity:0.9;max-width:540px;margin:0 auto 36px}
.premium-cta-btn{display:inline-block;padding:18px 40px;background:#fff;color:var(--p-accent);border-radius:9999px;font-family:var(--p-body);font-weight:700;font-size:1rem;text-decoration:none;transition:transform 0.2s,box-shadow 0.2s;box-shadow:0 8px 24px rgba(0,0,0,0.2)}
.premium-cta-btn:hover{transform:translateY(-2px);box-shadow:0 12px 32px rgba(0,0,0,0.3)}
`,
  html: `
<section class="premium-cta">
  <div class="premium-cta-card">
    <h2>{{HERO_LINE1}}</h2>
    <p>{{SUB_TEXT}}</p>
    <a class="premium-cta-btn" href="#contact">{{CTA_TEXT}} →</a>
  </div>
</section>
`,
};

// ============================================================
// CONTACT — Split form with info
// ============================================================
const contactSplit: PremiumPattern = {
  id: 'premium-contact-split',
  type: 'contact',
  name: 'Split Contact Form',
  fitness: 87,
  source: 'premium-library',
  fonts: ['Inter', 'Playfair Display'],
  features: ['split-layout', 'form', 'glassmorphic'],
  css: `
.premium-contact{padding:80px 24px;max-width:1100px;margin:0 auto;display:grid;grid-template-columns:1fr 1fr;gap:48px;align-items:flex-start}
@media(max-width:800px){.premium-contact{grid-template-columns:1fr;gap:32px}}
.premium-contact-info h2{font-family:var(--p-display);font-size:clamp(2rem,4vw,2.5rem);font-weight:700;color:var(--p-text);margin-bottom:16px;letter-spacing:-0.02em;line-height:1.15}
.premium-contact-info p{font-family:var(--p-body);font-size:1rem;line-height:1.7;color:var(--p-text-muted);margin-bottom:32px}
.premium-contact-info .row{display:flex;gap:12px;margin-bottom:20px;font-family:var(--p-body);font-size:0.9375rem;color:var(--p-text)}
.premium-contact-info .row strong{color:var(--p-accent);min-width:80px}
.premium-contact-form{background:var(--p-card-bg);backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);border:1px solid var(--p-card-border);border-radius:20px;padding:32px;display:flex;flex-direction:column;gap:16px}
.premium-contact-form input,.premium-contact-form textarea{padding:14px 16px;border:1px solid var(--p-input-border);border-radius:10px;font-size:0.9375rem;font-family:var(--p-body);background:var(--p-input-bg);color:var(--p-text);transition:border-color 0.2s}
.premium-contact-form input:focus,.premium-contact-form textarea:focus{outline:none;border-color:var(--p-accent)}
.premium-contact-form button{padding:16px 32px;background:var(--p-accent);color:var(--p-on-accent);border:none;border-radius:10px;font-size:0.9375rem;font-weight:600;cursor:pointer;font-family:var(--p-body);transition:transform 0.2s}
.premium-contact-form button:hover{transform:translateY(-2px)}
`,
  html: `
<section class="premium-contact" id="contact">
  <div class="premium-contact-info">
    <h2>Let's talk</h2>
    <p>We respond to every inquiry within one business day. Tell us about your project, your timeline, and the outcomes that matter.</p>
    <div class="row"><strong>Email</strong> hello@{{SLUG}}.com</div>
    <div class="row"><strong>Phone</strong> +1 (555) 010-0200</div>
    <div class="row"><strong>Studio</strong> 221 Market Street, Suite 400</div>
    <div class="row"><strong>Hours</strong> Mon–Fri, 9am–6pm PT</div>
  </div>
  <form class="premium-contact-form" onsubmit="event.preventDefault()">
    <input required type="text" placeholder="Your name" />
    <input required type="email" placeholder="Email address" />
    <input type="text" placeholder="Company (optional)" />
    <textarea required placeholder="Tell us about your project" rows="5"></textarea>
    <button type="submit">Send message</button>
  </form>
</section>
`,
};

// ============================================================
// FOOTER — Multi-column with social
// ============================================================
const footerMultiCol: PremiumPattern = {
  id: 'premium-footer-multicol',
  type: 'footer',
  name: 'Multi-Column Footer',
  fitness: 86,
  source: 'premium-library',
  fonts: ['Inter', 'Playfair Display'],
  features: ['multi-column', 'social-icons', 'newsletter'],
  css: `
.premium-footer{background:var(--p-bg-dark);border-top:1px solid var(--p-card-border);padding:64px 24px 32px}
.premium-footer-inner{max-width:1100px;margin:0 auto;display:grid;grid-template-columns:2fr 1fr 1fr 1fr;gap:48px}
@media(max-width:768px){.premium-footer-inner{grid-template-columns:1fr 1fr;gap:32px}}
@media(max-width:480px){.premium-footer-inner{grid-template-columns:1fr}}
.premium-footer-brand h3{font-family:var(--p-display);font-size:1.5rem;font-weight:700;color:var(--p-text);margin-bottom:12px;font-style:italic}
.premium-footer-brand p{font-family:var(--p-body);font-size:0.875rem;color:var(--p-text-muted);line-height:1.6;margin-bottom:16px}
.premium-footer-col h4{font-family:var(--p-body);font-size:0.75rem;font-weight:600;color:var(--p-text);text-transform:uppercase;letter-spacing:0.1em;margin-bottom:16px}
.premium-footer-col a{display:block;font-family:var(--p-body);font-size:0.875rem;color:var(--p-text-muted);text-decoration:none;margin-bottom:8px;transition:color 0.2s}
.premium-footer-col a:hover{color:var(--p-accent)}
.premium-footer-social{display:flex;gap:12px;margin-top:16px}
.premium-footer-social a{width:36px;height:36px;border-radius:50%;border:1px solid var(--p-card-border);display:flex;align-items:center;justify-content:center;font-size:14px;color:var(--p-text-muted);transition:all 0.2s}
.premium-footer-social a:hover{background:var(--p-accent);color:#fff;border-color:var(--p-accent)}
.premium-footer-bottom{max-width:1100px;margin:48px auto 0;padding-top:24px;border-top:1px solid var(--p-card-border);text-align:center;font-family:var(--p-body);font-size:0.8125rem;color:var(--p-text-muted)}
`,
  html: `
<footer class="premium-footer">
  <div class="premium-footer-inner">
    <div class="premium-footer-brand">
      <h3>{{BUSINESS_NAME}}</h3>
      <p>{{SUB_TEXT}}</p>
      <div class="premium-footer-social">
        <a href="#" aria-label="Twitter">𝕏</a>
        <a href="#" aria-label="Instagram">📷</a>
        <a href="#" aria-label="LinkedIn">in</a>
        <a href="#" aria-label="GitHub">⌥</a>
      </div>
    </div>
    <div class="premium-footer-col">
      <h4>Company</h4>
      <a href="#about">About</a>
      <a href="#features">Services</a>
      <a href="#gallery">Work</a>
      <a href="#contact">Contact</a>
    </div>
    <div class="premium-footer-col">
      <h4>Resources</h4>
      <a href="#">Blog</a>
      <a href="#faq">FAQ</a>
      <a href="#">Help</a>
      <a href="#">Privacy</a>
    </div>
    <div class="premium-footer-col">
      <h4>Connect</h4>
      <a href="#">Twitter</a>
      <a href="#">Instagram</a>
      <a href="#">LinkedIn</a>
      <a href="#">Email</a>
    </div>
  </div>
  <div class="premium-footer-bottom">© {{YEAR}} {{BUSINESS_NAME}}. All rights reserved.</div>
</footer>
`,
};

// ============================================================
// PARTNERS — Logo strip
// ============================================================
const partnersStrip: PremiumPattern = {
  id: 'premium-partners-strip',
  type: 'partners',
  name: 'Partner Logo Strip',
  fitness: 85,
  source: 'premium-library',
  fonts: ['Inter'],
  features: ['logo-strip', 'centered'],
  css: `
.premium-prt{padding:48px 24px;max-width:1100px;margin:0 auto;text-align:center}
.premium-prt h2{font-family:var(--p-body);font-size:0.75rem;color:var(--p-text-muted);text-transform:uppercase;letter-spacing:0.15em;margin-bottom:32px;font-weight:500}
.premium-prt-list{display:flex;flex-wrap:wrap;justify-content:center;gap:48px;align-items:center}
.premium-prt-item{font-family:var(--p-display);font-size:1.25rem;font-weight:600;color:var(--p-text-muted);opacity:0.6;transition:opacity 0.2s}
.premium-prt-item:hover{opacity:1}
`,
  html: `
<section class="premium-prt">
  <h2>Trusted by teams at</h2>
  <div class="premium-prt-list">
    <span class="premium-prt-item">Northwind</span>
    <span class="premium-prt-item">Helios</span>
    <span class="premium-prt-item">Aurora</span>
    <span class="premium-prt-item">Lumen</span>
    <span class="premium-prt-item">Atlas</span>
    <span class="premium-prt-item">Verdant</span>
  </div>
</section>
`,
};

// ============================================================
// TEAM — Grid with avatars
// ============================================================
const teamGrid: PremiumPattern = {
  id: 'premium-team-grid',
  type: 'team',
  name: 'Team Grid with Avatars',
  fitness: 84,
  source: 'premium-library',
  fonts: ['Inter', 'Playfair Display'],
  features: ['grid', 'avatars', 'rounded'],
  css: `
.premium-team{padding:80px 24px;max-width:1100px;margin:0 auto}
.premium-team-head{text-align:center;margin-bottom:40px}
.premium-team-head h2{font-family:var(--p-display);font-size:clamp(2rem,4vw,3rem);font-weight:700;color:var(--p-text);letter-spacing:-0.03em;margin-bottom:12px}
.premium-team-head p{font-family:var(--p-body);font-size:1.0625rem;color:var(--p-text-muted)}
.premium-team-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:32px}
.premium-team-member{text-align:center}
.premium-team-member img{width:140px;height:140px;border-radius:50%;object-fit:cover;margin:0 auto 20px;display:block;border:3px solid var(--p-card-border)}
.premium-team-member h3{font-family:var(--p-display);font-size:1.125rem;font-weight:600;color:var(--p-text);margin-bottom:4px}
.premium-team-member .role{font-family:var(--p-body);font-size:0.8125rem;color:var(--p-accent);text-transform:uppercase;letter-spacing:0.08em;font-weight:600;margin-bottom:8px}
.premium-team-member p{font-family:var(--p-body);font-size:0.875rem;color:var(--p-text-muted);line-height:1.5;max-width:200px;margin:0 auto}
`,
  html: `
<section class="premium-team" id="team">
  <div class="premium-team-head">
    <h2>Meet the team</h2>
    <p>The people behind the work.</p>
  </div>
  <div class="premium-team-grid">
    <div class="premium-team-member"><img src="https://picsum.photos/seed/t1/280/280" alt="Maya Chen"/><h3>Maya Chen</h3><div class="role">Founder & CD</div><p>15 years shaping brands at the intersection of editorial and product.</p></div>
    <div class="premium-team-member"><img src="https://picsum.photos/seed/t2/280/280" alt="Daniel Okoro"/><h3>Daniel Okoro</h3><div class="role">Principal Eng</div><p>Ships resilient systems with a bias for boring, proven tech.</p></div>
    <div class="premium-team-member"><img src="https://picsum.photos/seed/t3/280/280" alt="Priya Raman"/><h3>Priya Raman</h3><div class="role">Head of Strategy</div><p>Former McKinsey. Turns business problems into design briefs.</p></div>
    <div class="premium-team-member"><img src="https://picsum.photos/seed/t4/280/280" alt="Jonas Weber"/><h3>Jonas Weber</h3><div class="role">Design Lead</div><p>Editorial typography obsessive. Ex-Pentagram.</p></div>
  </div>
</section>
`,
};

// ============================================================
// BLOG — Three card grid
// ============================================================
const blogThreeCard: PremiumPattern = {
  id: 'premium-blog-three-card',
  type: 'blog',
  name: 'Three Card Blog Grid',
  fitness: 83,
  source: 'premium-library',
  fonts: ['Inter', 'Playfair Display'],
  features: ['grid', 'image-cards', 'hover-effect'],
  css: `
.premium-blog{padding:80px 24px;max-width:1100px;margin:0 auto}
.premium-blog-head{display:flex;justify-content:space-between;align-items:flex-end;margin-bottom:48px;gap:24px;flex-wrap:wrap}
.premium-blog-head h2{font-family:var(--p-display);font-size:clamp(2rem,4vw,2.5rem);font-weight:700;color:var(--p-text);letter-spacing:-0.03em}
.premium-blog-head a{font-family:var(--p-body);font-size:0.875rem;color:var(--p-accent);text-decoration:none;font-weight:600}
.premium-blog-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:24px}
.premium-blog-card{background:var(--p-card-bg);border:1px solid var(--p-card-border);border-radius:16px;overflow:hidden;transition:transform 0.2s,border-color 0.2s}
.premium-blog-card:hover{transform:translateY(-4px);border-color:var(--p-accent)}
.premium-blog-card .img{aspect-ratio:16/10;background-size:cover;background-position:center}
.premium-blog-card .body{padding:24px}
.premium-blog-card .meta{font-size:0.75rem;color:var(--p-accent);text-transform:uppercase;letter-spacing:0.08em;font-weight:600;margin-bottom:8px}
.premium-blog-card h3{font-family:var(--p-display);font-size:1.125rem;font-weight:600;color:var(--p-text);margin-bottom:8px;line-height:1.3}
.premium-blog-card p{font-family:var(--p-body);font-size:0.875rem;line-height:1.55;color:var(--p-text-muted)}
`,
  html: `
<section class="premium-blog" id="blog">
  <div class="premium-blog-head">
    <h2>From the journal</h2>
    <a href="#">View all posts →</a>
  </div>
  <div class="premium-blog-grid">
    <article class="premium-blog-card">
      <div class="img" style="background-image:url('https://picsum.photos/seed/b1/600/375')"></div>
      <div class="body">
        <div class="meta">Article · 6 min</div>
        <h3>Why your landing page converts at 1.2%</h3>
        <p>A teardown of the seven most common conversion killers, with concrete fixes for each.</p>
      </div>
    </article>
    <article class="premium-blog-card">
      <div class="img" style="background-image:url('https://picsum.photos/seed/b2/600/375')"></div>
      <div class="body">
        <div class="meta">Article · 4 min</div>
        <h3>The design system ROI nobody talks about</h3>
        <p>How a documented component library pays back 4x in shipping speed.</p>
      </div>
    </article>
    <article class="premium-blog-card">
      <div class="img" style="background-image:url('https://picsum.photos/seed/b3/600/375')"></div>
      <div class="body">
        <div class="meta">Article · 8 min</div>
        <h3>Accessibility is a feature, not a checklist</h3>
        <p>Practical patterns for keyboard, screen reader, and reduced-motion users.</p>
      </div>
    </article>
  </div>
</section>
`,
};

// ============================================================
// NAV — Minimal centered (alternative layout)
// ============================================================
const navMinimal: PremiumPattern = {
  id: 'premium-nav-minimal',
  type: 'nav',
  name: 'Minimal Centered Nav',
  fitness: 93,
  source: 'premium-library',
  fonts: ['Inter'],
  features: ['minimal', 'centered', 'clean'],
  css: `
.premium-nav-min{position:fixed;top:0;left:0;right:0;z-index:100;display:flex;align-items:center;justify-content:space-between;padding:1rem 2rem;background:var(--p-glass-bg);backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px);border-bottom:1px solid var(--p-card-border)}
.premium-nav-min-left{font-family:var(--p-body);font-size:1.125rem;font-weight:700;color:var(--p-text);letter-spacing:-0.02em}
.premium-nav-min-center{display:none;gap:2rem}
@media(min-width:768px){.premium-nav-min-center{display:flex}}
.premium-nav-min-link{color:var(--p-text-muted);font-size:0.875rem;font-weight:500;cursor:pointer;transition:color 0.2s;background:none;border:none;font-family:var(--p-body)}
.premium-nav-min-link:hover{color:var(--p-text)}
.premium-nav-min-link.active{color:var(--p-accent)}
.premium-nav-min-right{display:none;background:var(--p-accent);color:var(--p-on-accent);font-size:0.8125rem;font-weight:600;padding:0.5rem 1.25rem;border-radius:8px;cursor:pointer;border:none;transition:transform 0.2s;font-family:var(--p-body)}
@media(min-width:768px){.premium-nav-min-right{display:block}}
.premium-nav-min-right:hover{transform:translateY(-1px)}
.premium-nav-min-hamburger{display:flex;flex-direction:column;gap:4px;cursor:pointer}
@media(min-width:768px){.premium-nav-min-hamburger{display:none}}
.premium-nav-min-hamburger span{width:20px;height:2px;background:var(--p-text);border-radius:2px}
`,
  html: `
<nav class="premium-nav-min">
  <div class="premium-nav-min-left">{{BUSINESS_NAME}}</div>
  <div class="premium-nav-min-center">
    <button class="premium-nav-min-link active" data-target="features">Features</button>
    <button class="premium-nav-min-link" data-target="about">About</button>
    <button class="premium-nav-min-link" data-target="pricing">Pricing</button>
    <button class="premium-nav-min-link" data-target="contact">Contact</button>
  </div>
  <button class="premium-nav-min-right" data-target="contact">{{CTA_TEXT}}</button>
  <div class="premium-nav-min-hamburger"><span></span><span></span><span></span></div>
</nav>
`,
  js: `
(function(){
  // Smooth scroll for ALL nav links with data-target
  document.querySelectorAll('[data-target]').forEach(function(el){
    el.addEventListener('click',function(){
      var target=this.getAttribute('data-target');
      var section=document.getElementById(target);
      if(section)section.scrollIntoView({behavior:'smooth',block:'start'});
    });
  });
  // Update active nav link on scroll
  var navLinks=document.querySelectorAll('.premium-nav-min-link');
  var sections=document.querySelectorAll('section[id]');
  function updateActive(){
    var sy=window.scrollY+120;
    sections.forEach(function(sec){
      var id=sec.getAttribute('id');
      if(sy>=sec.offsetTop&&sy<sec.offsetTop+sec.offsetHeight){
        navLinks.forEach(function(l){
          if(l.getAttribute('data-target')===id)l.classList.add('active');
          else l.classList.remove('active');
        });
      }
    });
  }
  window.addEventListener('scroll',updateActive);
  // Hamburger — scroll to features on mobile
  var hamburger=document.querySelector('.premium-nav-min-hamburger');
  if(hamburger)hamburger.addEventListener('click',function(){
    document.getElementById('features')?.scrollIntoView({behavior:'smooth'});
  });
})();
`,
};

// ============================================================
// HERO — Editorial split (image left, text right)
// ============================================================
const heroEditorialSplit: PremiumPattern = {
  id: 'premium-hero-editorial-split',
  type: 'hero',
  name: 'Editorial Split Hero',
  fitness: 95,
  source: 'premium-library',
  fonts: ['Inter', 'Playfair Display'],
  features: ['editorial', 'split-layout', 'image-side', 'magazine-style'],
  css: `
.premium-hero-es{display:grid;grid-template-columns:1fr 1fr;min-height:100vh;min-height:100dvh;background:var(--p-bg)}
@media(max-width:900px){.premium-hero-es{grid-template-columns:1fr}}
.premium-hero-es-text{padding:120px 80px;display:flex;flex-direction:column;justify-content:center;order:2}
@media(max-width:900px){.premium-hero-es-text{order:2;padding:60px 24px;text-align:center;align-items:center}}
.premium-hero-es-meta{font-size:11px;text-transform:uppercase;letter-spacing:0.2em;color:var(--p-accent);margin-bottom:16px;font-weight:600;font-family:var(--p-body)}
.premium-hero-es-text h1{font-family:var(--p-display);font-size:clamp(2.5rem,6vw,5rem);font-weight:700;line-height:1.02;letter-spacing:-0.03em;margin-bottom:24px;color:var(--p-text)}
.premium-hero-es-text h1 em{font-style:italic;color:var(--p-accent);font-weight:400}
.premium-hero-es-text p{font-family:var(--p-body);font-size:1.125rem;line-height:1.7;color:var(--p-text-muted);margin-bottom:40px;max-width:480px}
.premium-hero-es-cta{display:inline-block;padding:16px 32px;background:var(--p-accent);color:var(--p-on-accent);border-radius:8px;font-family:var(--p-body);font-weight:600;font-size:0.9375rem;text-decoration:none;transition:transform 0.2s}
.premium-hero-es-cta:hover{transform:translateY(-2px)}
.premium-hero-es-img{background:linear-gradient(135deg,var(--p-accent)22,var(--p-accent)11),url('https://picsum.photos/seed/{{SLUG}}-editorial/800/1000') center/cover;min-height:500px;order:1}
@media(max-width:900px){.premium-hero-es-img{min-height:300px;order:1}}
`,
  html: `
<section class="premium-hero-es" id="hero">
  <div class="premium-hero-es-text">
    <div class="premium-hero-es-meta">{{BUSINESS_NAME}} · Est. {{YEAR}}</div>
    <h1>{{HERO_LINE1}}<br/><em>{{HERO_LINE2}}</em></h1>
    <p>{{SUB_TEXT}}</p>
    <a class="premium-hero-es-cta" href="#features">{{CTA_TEXT}} →</a>
  </div>
  <div class="premium-hero-es-img"></div>
</section>
`,
};

// ============================================================
// HERO — Bold display (huge text, dark bg, minimal)
// ============================================================
const heroBoldDisplay: PremiumPattern = {
  id: 'premium-hero-bold-display',
  type: 'hero',
  name: 'Bold Display Hero',
  fitness: 94,
  source: 'premium-library',
  fonts: ['Inter', 'Anton'],
  features: ['bold', 'huge-typography', 'dark-bg', 'minimal', 'ken-burns'],
  css: `
.premium-hero-bd{position:relative;min-height:100vh;min-height:100dvh;background:var(--p-bg-dark);display:flex;flex-direction:column;justify-content:center;overflow:hidden}
.premium-hero-bd::before{content:'{{BUSINESS_NAME}}';position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);font-family:'Anton',sans-serif;font-size:clamp(120px,30vw,400px);font-weight:900;color:var(--p-accent);opacity:0.04;white-space:nowrap;pointer-events:none;letter-spacing:-0.05em;line-height:1;text-transform:uppercase}
.premium-hero-bd-inner{position:relative;z-index:10;text-align:center;padding:0 24px;max-width:1200px;margin:0 auto}
.premium-hero-bd h1{font-family:'Anton',sans-serif;font-size:clamp(3rem,10vw,8rem);font-weight:900;line-height:0.9;letter-spacing:-0.04em;margin-bottom:32px;color:var(--p-text);text-transform:uppercase}
.premium-hero-bd h1 span{color:var(--p-accent)}
.premium-hero-bd p{font-family:var(--p-body);font-size:clamp(0.9375rem,1.5vw,1.125rem);color:var(--p-text-muted);max-width:580px;margin:0 auto 40px;line-height:1.6}
.premium-hero-bd-cta{display:inline-block;padding:20px 48px;background:var(--p-accent);color:var(--p-on-accent);border-radius:8px;font-family:var(--p-body);font-weight:700;font-size:1rem;text-decoration:none;text-transform:uppercase;letter-spacing:0.05em;transition:transform 0.2s}
.premium-hero-bd-cta:hover{transform:translateY(-2px) scale(1.02)}
`,
  html: `
<section class="premium-hero-bd" id="hero">
  <div class="premium-hero-bd-inner">
    <h1>{{HERO_LINE1}}<br/><span>{{HERO_LINE2}}</span></h1>
    <p>{{SUB_TEXT}}</p>
    <a class="premium-hero-bd-cta" href="#features">{{CTA_TEXT}}</a>
  </div>
</section>
`,
};

// ============================================================
// HERO — Playful centered (rounded, pastel, friendly)
// ============================================================
const heroPlayfulCentered: PremiumPattern = {
  id: 'premium-hero-playful-centered',
  type: 'hero',
  name: 'Playful Centered Hero',
  fitness: 92,
  source: 'premium-library',
  fonts: ['Inter', 'Poppins'],
  features: ['playful', 'rounded', 'friendly', 'pastel', 'fun'],
  css: `
.premium-hero-pc{position:relative;min-height:100vh;min-height:100dvh;display:flex;align-items:center;justify-content:center;text-align:center;overflow:hidden;background:linear-gradient(180deg,var(--p-bg) 0%,var(--p-bg-dark) 100%)}
.premium-hero-pc::before{content:'✦';position:absolute;top:15%;left:10%;font-size:48px;color:var(--p-accent);opacity:0.4;animation:premiumSpin 8s linear infinite}
.premium-hero-pc::after{content:'✦';position:absolute;bottom:20%;right:12%;font-size:64px;color:var(--p-accent);opacity:0.3;animation:premiumSpin 12s linear infinite reverse}
@keyframes premiumSpin{from{transform:rotate(0)}to{transform:rotate(360deg)}}
.premium-hero-pc-inner{position:relative;z-index:10;max-width:780px;margin:0 auto;padding:0 24px}
.premium-hero-pc h1{font-family:'Poppins',sans-serif;font-size:clamp(2.5rem,7vw,5rem);font-weight:700;line-height:1.05;letter-spacing:-0.02em;margin-bottom:20px;color:var(--p-text)}
.premium-hero-pc h1 em{font-style:italic;color:var(--p-accent);font-weight:400}
.premium-hero-pc p{font-family:var(--p-body);font-size:1.125rem;line-height:1.6;color:var(--p-text-muted);margin-bottom:36px}
.premium-hero-pc-cta{display:inline-block;padding:18px 40px;background:var(--p-accent);color:var(--p-on-accent);border-radius:9999px;font-family:var(--p-body);font-weight:700;font-size:1rem;text-decoration:none;box-shadow:0 8px 24px var(--p-accent-shadow);transition:transform 0.2s,box-shadow 0.2s}
.premium-hero-pc-cta:hover{transform:translateY(-3px);box-shadow:0 12px 32px var(--p-accent-shadow)}
`,
  html: `
<section class="premium-hero-pc" id="hero">
  <div class="premium-hero-pc-inner">
    <h1>{{HERO_LINE1}} <em>{{HERO_LINE2}}</em></h1>
    <p>{{SUB_TEXT}}</p>
    <a class="premium-hero-pc-cta" href="#features">{{CTA_TEXT}} ✨</a>
  </div>
</section>
`,
};

// ============================================================
// FEATURES — Minimal numbered list (alternative)
// ============================================================
const featuresMinimalList: PremiumPattern = {
  id: 'premium-features-minimal-list',
  type: 'features',
  name: 'Minimal Numbered Features',
  fitness: 91,
  source: 'premium-library',
  fonts: ['Inter', 'Playfair Display'],
  features: ['minimal', 'numbered', 'list', 'editorial'],
  css: `
.premium-features-ml{padding:80px 24px;max-width:900px;margin:0 auto}
.premium-features-ml h2{font-family:var(--p-display);font-size:clamp(2rem,4vw,3rem);font-weight:700;color:var(--p-text);letter-spacing:-0.03em;margin-bottom:48px;text-align:center}
.premium-features-ml-item{display:grid;grid-template-columns:60px 1fr;gap:24px;padding:32px 0;border-bottom:1px solid var(--p-card-border);align-items:start}
.premium-features-ml-item:last-child{border-bottom:none}
.premium-features-ml-num{font-family:var(--p-display);font-size:2.5rem;font-weight:700;color:var(--p-accent);line-height:1}
.premium-features-ml-item h3{font-family:var(--p-display);font-size:1.375rem;font-weight:600;color:var(--p-text);margin-bottom:8px}
.premium-features-ml-item p{font-family:var(--p-body);font-size:0.9375rem;line-height:1.6;color:var(--p-text-muted)}
`,
  html: `
<section class="premium-features-ml" id="features">
  <h2>What we do</h2>
  <div class="premium-features-ml-item">
    <div class="premium-features-ml-num">01</div>
    <div><h3>Strategy & Discovery</h3><p>We dig deep into your business, users, and goals to build a foundation that ensures every design decision serves a purpose.</p></div>
  </div>
  <div class="premium-features-ml-item">
    <div class="premium-features-ml-num">02</div>
    <div><h3>Design & Prototyping</h3><p>From wireframes to high-fidelity prototypes, we craft interfaces that feel intuitive and look stunning.</p></div>
  </div>
  <div class="premium-features-ml-item">
    <div class="premium-features-ml-num">03</div>
    <div><h3>Development & Launch</h3><p>Clean, performant code that scales. We ship fast, test thoroughly, and deploy with confidence.</p></div>
  </div>
</section>
`,
};

// ============================================================
// ABOUT — Centered text (alternative to split)
// ============================================================
const aboutCentered: PremiumPattern = {
  id: 'premium-about-centered',
  type: 'about',
  name: 'Centered About Section',
  fitness: 88,
  source: 'premium-library',
  fonts: ['Inter', 'Playfair Display'],
  features: ['centered', 'text-only', 'editorial'],
  css: `
.premium-about-c{padding:80px 24px;max-width:720px;margin:0 auto;text-align:center}
.premium-about-c h2{font-family:var(--p-display);font-size:clamp(2rem,4vw,3rem);font-weight:700;color:var(--p-text);letter-spacing:-0.03em;margin-bottom:24px}
.premium-about-c h2 em{font-style:italic;color:var(--p-accent)}
.premium-about-c p{font-family:var(--p-body);font-size:1.125rem;line-height:1.8;color:var(--p-text-muted);margin-bottom:16px}
.premium-about-c .sig{font-family:var(--p-display);font-style:italic;font-size:1.25rem;color:var(--p-text);margin-top:32px}
`,
  html: `
<section class="premium-about-c" id="about">
  <h2>Our <em>philosophy</em></h2>
  <p>We believe great work comes from understanding the problem deeply, collaborating closely, and shipping with care. Every project is an opportunity to create something that lasts.</p>
  <p>From first sketch to launched product, we partner end-to-end — strategy, design, engineering. No handoffs, no silos, just a team that cares about your outcome.</p>
  <div class="sig">— The {{BUSINESS_NAME}} Team</div>
</section>
`,
};

// ============================================================
// Export all premium patterns
// ============================================================
export const PREMIUM_PATTERNS: PremiumPattern[] = [
  navGlassmorphic,
  navMinimal,
  heroCinematic,
  heroEditorialSplit,
  heroBoldDisplay,
  heroPlayfulCentered,
  featuresGlassmorphic,
  featuresMinimalList,
  aboutSplit,
  aboutCentered,
  statsGradient,
  testimonialsCards,
  galleryMasonry,
  pricingThreeTier,
  teamGrid,
  blogThreeCard,
  faqAccordion,
  contactSplit,
  ctaGradient,
  footerMultiCol,
  partnersStrip,
];

/** Get all premium patterns for a given section type */
export function getPremiumPatterns(type: string): PremiumPattern[] {
  return PREMIUM_PATTERNS.filter(p => p.type === type);
}

/** Get the best premium pattern for a section type */
export function getBestPremiumPattern(type: string): PremiumPattern | null {
  const matching = getPremiumPatterns(type).sort((a, b) => b.fitness - a.fitness);
  return matching[0] || null;
}

/** Get all unique font families from premium patterns */
export function getAllPremiumFonts(): string[] {
  const fonts = new Set<string>();
  for (const p of PREMIUM_PATTERNS) {
    p.fonts.forEach(f => fonts.add(f));
  }
  return Array.from(fonts);
}

/** Get pattern by ID */
export function getPremiumPatternById(id: string): PremiumPattern | null {
  return PREMIUM_PATTERNS.find(p => p.id === id) || null;
}
